/****************************************************************************
**
** Metadata for AGRAMTABLib generated by dumpcpp from type library
** agramtab.tlb
**
****************************************************************************/

#define QAX_DUMPCPP_AGRAMTABLIB_NOINLINES
#include "agramtab.h"

using namespace AGRAMTABLib;

static const uint qt_meta_data_AGRAMTABLib__RusGramTab[] = {

 // content:
       1,       // revision
       0,       // classname
       1,    10, // classinfo
       21,    12, // methods
       2,    117, // properties
       8,    123, // enums/sets

 // classinfo: key, value
       24, 36, 

 // signals: signature, parameters, type, tag, flags
       45, 84, 106, 107, 5,
       108, 133, 138, 139, 5,
       140, 166, 181, 182, 5,

 // slots: signature, parameters, type, tag, flags
       183, 214, 234, 238, 9,
       239, 263, 273, 283, 9,
       284, 309, 314, 322, 9,
       323, 352, 365, 369, 9,
       370, 409, 428, 432, 9,
       433, 500, 523, 527, 9,
       528, 549, 559, 569, 9,
       570, 595, 605, 610, 9,
       611, 636, 649, 657, 9,
       658, 693, 715, 719, 9,
       720, 757, 779, 783, 9,
       784, 833, 884, 888, 9,
       889, 930, 952, 956, 9,
       957, 982, 991, 999, 9,
       1000, 1039, 1061, 1065, 9,
       1066, 1073, 1074, 1075, 9,
       1076, 1124, 1149, 1150, 9,
       1151, 1204, 1229, 1233, 9,

 // properties: name, type, flags
       1234, 1248, 0x02005001, 		 // int GrammemsCount
       1252, 1270, 0x03005001, 		 // uint PartOfSpeechCount

 // enums: name, flags, count, data
       1275, 0x0, 12, 155, 
       1317, 0x0, 3, 179, 
       1359, 0x0, 34, 185, 
       1369, 0x0, 17, 253, 
       1385, 0x0, 62, 287, 
       1395, 0x0, 17, 411, 
       1411, 0x0, 57, 445, 
       1421, 0x0, 22, 559, 

 // enum data: key, value
       1437, AGRAMTABLib::VERB_PERS_T,
       1449, AGRAMTABLib::ADVERB_PARTICIPLE_T,
       1469, AGRAMTABLib::PARTICIPLE_SHORT_T,
       1488, AGRAMTABLib::ADJ_SHORT_T,
       1500, AGRAMTABLib::PREDK_T,
       1508, AGRAMTABLib::PARTICIPLE_T,
       1521, AGRAMTABLib::INFINITIVE_T,
       1534, AGRAMTABLib::INP_T,
       1540, AGRAMTABLib::DASH_T,
       1547, AGRAMTABLib::UNDETACHED_ADJ_PATIC,
       1568, AGRAMTABLib::COMPARATIVE_T,
       1582, AGRAMTABLib::COPUL_T,
       1590, AGRAMTABLib::VERBSATZ_T,
       1601, AGRAMTABLib::PARTIZIPIALSATZ_T,
       1619, AGRAMTABLib::INFINITIVSATZ_T,
       1635, AGRAMTABLib::eSingular,
       1645, AGRAMTABLib::ePlural,
       1653, AGRAMTABLib::eMasculinum,
       1665, AGRAMTABLib::eFeminum,
       1674, AGRAMTABLib::eAnimative,
       1685, AGRAMTABLib::ePerfective,
       1697, AGRAMTABLib::eNominative,
       1709, AGRAMTABLib::eObjectCase,
       1721, AGRAMTABLib::eNarrative,
       1732, AGRAMTABLib::eGeographics,
       1745, AGRAMTABLib::eProper,
       1753, AGRAMTABLib::ePersonalPronoun,
       1770, AGRAMTABLib::ePossessive,
       1782, AGRAMTABLib::ePredicative,
       1795, AGRAMTABLib::eUncountable,
       1808, AGRAMTABLib::eReflexivePronoun,
       1826, AGRAMTABLib::eDemonstrativePronoun,
       1848, AGRAMTABLib::eMass,
       1854, AGRAMTABLib::eComparativ,
       1866, AGRAMTABLib::eSupremum,
       1876, AGRAMTABLib::eFirstPerson,
       1889, AGRAMTABLib::eSecondPerson,
       1903, AGRAMTABLib::eThirdPerson,
       1916, AGRAMTABLib::ePresentIndef,
       1930, AGRAMTABLib::eInfinitive,
       1942, AGRAMTABLib::ePastIndef,
       1953, AGRAMTABLib::ePastParticiple,
       1969, AGRAMTABLib::eGerund,
       1977, AGRAMTABLib::eFuturum,
       1986, AGRAMTABLib::eConditional,
       1999, AGRAMTABLib::eApostropheS,
       2012, AGRAMTABLib::eApostrophe,
       2024, AGRAMTABLib::eNames,
       2031, AGRAMTABLib::eOrganisation,
       2045, AGRAMTABLib::eNOUN,
       2051, AGRAMTABLib::eADJ,
       2056, AGRAMTABLib::eVERB,
       2062, AGRAMTABLib::eVBE,
       2067, AGRAMTABLib::eMOD,
       2072, AGRAMTABLib::eNUMERAL,
       2081, AGRAMTABLib::eCONJ,
       2087, AGRAMTABLib::eINTERJ,
       2095, AGRAMTABLib::ePREP,
       2101, AGRAMTABLib::ePARTICLE,
       2111, AGRAMTABLib::eART,
       2116, AGRAMTABLib::eADV,
       2121, AGRAMTABLib::ePN,
       2125, AGRAMTABLib::eORDNUM,
       2133, AGRAMTABLib::ePRON,
       2139, AGRAMTABLib::ePOSS,
       2145, AGRAMTABLib::ePN_ADJ,
       2153, AGRAMTABLib::gNoaUnk,
       2161, AGRAMTABLib::gPredikBenutz,
       2175, AGRAMTABLib::gProUnk,
       2183, AGRAMTABLib::gTmpUnk,
       2191, AGRAMTABLib::gNac,
       2196, AGRAMTABLib::gMou,
       2201, AGRAMTABLib::gCou,
       2206, AGRAMTABLib::gGeo,
       2211, AGRAMTABLib::gWasser,
       2219, AGRAMTABLib::gGeb,
       2224, AGRAMTABLib::gStd,
       2229, AGRAMTABLib::gLok,
       2234, AGRAMTABLib::gVor,
       2239, AGRAMTABLib::gSichAcc,
       2248, AGRAMTABLib::gSichDat,
       2257, AGRAMTABLib::gSchwach,
       2266, AGRAMTABLib::gNichtSchwach,
       2280, AGRAMTABLib::gModal,
       2287, AGRAMTABLib::gAuxiliar,
       2297, AGRAMTABLib::gKonj1,
       2304, AGRAMTABLib::gKonj2,
       2311, AGRAMTABLib::gPartizip1,
       2322, AGRAMTABLib::gPartizip2,
       2333, AGRAMTABLib::gZuVerbForm,
       2345, AGRAMTABLib::gImperativ,
       2356, AGRAMTABLib::gPraeteritum,
       2369, AGRAMTABLib::gPrasens,
       2378, AGRAMTABLib::gGrundform,
       2389, AGRAMTABLib::gKomparativ,
       2401, AGRAMTABLib::gSuperlativ,
       2413, AGRAMTABLib::gProportionalKonjunktion,
       2438, AGRAMTABLib::gInfinitiv,
       2449, AGRAMTABLib::gVergleichsKonjunktion,
       2472, AGRAMTABLib::gNebenordnende,
       2487, AGRAMTABLib::gUnterordnende,
       2502, AGRAMTABLib::gPersonal,
       2512, AGRAMTABLib::gDemonstrativ,
       2526, AGRAMTABLib::gInterrogativ,
       2540, AGRAMTABLib::gPossessiv,
       2551, AGRAMTABLib::gReflexiv,
       2561, AGRAMTABLib::gRinPronomen,
       2574, AGRAMTABLib::gAlgPronomen,
       2587, AGRAMTABLib::gAdjektiveOhneArtikel,
       2609, AGRAMTABLib::gAdjektiveMitUnbestimmte,
       2634, AGRAMTABLib::gAdjektiveMitBestimmte,
       2657, AGRAMTABLib::gErstePerson,
       2670, AGRAMTABLib::gZweitePerson,
       2684, AGRAMTABLib::gDrittePerson,
       2698, AGRAMTABLib::gFeminin,
       2707, AGRAMTABLib::gMaskulin,
       2717, AGRAMTABLib::gNeutrum,
       2726, AGRAMTABLib::gPlural,
       2734, AGRAMTABLib::gSingular,
       2744, AGRAMTABLib::gNominativ,
       2755, AGRAMTABLib::gGenitiv,
       2764, AGRAMTABLib::gDativ,
       2771, AGRAMTABLib::gAkkusativ,
       2782, AGRAMTABLib::gAbbreviation,
       2796, AGRAMTABLib::gEinwohner,
       2807, AGRAMTABLib::gTransitiv,
       2818, AGRAMTABLib::gIntransitiv,
       2831, AGRAMTABLib::gImpersonal,
       2843, AGRAMTABLib::gART,
       2848, AGRAMTABLib::gADJ,
       2853, AGRAMTABLib::gADV,
       2858, AGRAMTABLib::gEIG,
       2863, AGRAMTABLib::gSUB,
       2868, AGRAMTABLib::gVER,
       2873, AGRAMTABLib::gPA1,
       2878, AGRAMTABLib::gPA2,
       2883, AGRAMTABLib::gPRONOMEN,
       2893, AGRAMTABLib::gPRP,
       2898, AGRAMTABLib::gKON,
       2903, AGRAMTABLib::gNEG,
       2908, AGRAMTABLib::gINJ,
       2913, AGRAMTABLib::gZAL,
       2918, AGRAMTABLib::gZUS,
       2923, AGRAMTABLib::gPRO_BEG,
       2932, AGRAMTABLib::gZU_INFINITIV,
       2946, AGRAMTABLib::rPlural,
       2954, AGRAMTABLib::rSingular,
       2964, AGRAMTABLib::rAllNumbers,
       2976, AGRAMTABLib::rNominativ,
       2987, AGRAMTABLib::rGenitiv,
       2996, AGRAMTABLib::rDativ,
       3003, AGRAMTABLib::rAccusativ,
       3014, AGRAMTABLib::rInstrumentalis,
       3030, AGRAMTABLib::rLocativ,
       3039, AGRAMTABLib::rVocativ,
       3048, AGRAMTABLib::rAllCases,
       3058, AGRAMTABLib::rMasculinum,
       3070, AGRAMTABLib::rFeminum,
       3079, AGRAMTABLib::rNeutrum,
       3088, AGRAMTABLib::rMascFem,
       3097, AGRAMTABLib::rAllGenders,
       3109, AGRAMTABLib::rPresentTense,
       3123, AGRAMTABLib::rFutureTense,
       3136, AGRAMTABLib::rPastTense,
       3147, AGRAMTABLib::rAllTimes,
       3157, AGRAMTABLib::rFirstPerson,
       3170, AGRAMTABLib::rSecondPerson,
       3184, AGRAMTABLib::rThirdPerson,
       3197, AGRAMTABLib::rAllPersons,
       3209, AGRAMTABLib::rImperative,
       3221, AGRAMTABLib::rAnimative,
       3232, AGRAMTABLib::rNonAnimative,
       3246, AGRAMTABLib::rAllAnimative,
       3260, AGRAMTABLib::rComparative,
       3273, AGRAMTABLib::rPerfective,
       3285, AGRAMTABLib::rNonPerfective,
       3300, AGRAMTABLib::rNonTransitive,
       3315, AGRAMTABLib::rTransitive,
       3327, AGRAMTABLib::rActiveVoice,
       3340, AGRAMTABLib::rPassiveVoice,
       3354, AGRAMTABLib::rIndeclinable,
       3368, AGRAMTABLib::rInitialism,
       3380, AGRAMTABLib::rPatronymic,
       3392, AGRAMTABLib::rToponym,
       3401, AGRAMTABLib::rOrganisation,
       3415, AGRAMTABLib::rQualitative,
       3428, AGRAMTABLib::rDeFactoSingTantum,
       3447, AGRAMTABLib::rInterrogative,
       3462, AGRAMTABLib::rDemonstrative,
       3477, AGRAMTABLib::rName,
       3483, AGRAMTABLib::rSurName,
       3492, AGRAMTABLib::rImpersonal,
       3504, AGRAMTABLib::rSlang,
       3511, AGRAMTABLib::rMisprint,
       3521, AGRAMTABLib::rColloquial,
       3533, AGRAMTABLib::rPossessive,
       3545, AGRAMTABLib::rArchaism,
       3555, AGRAMTABLib::rSecondCase,
       3567, AGRAMTABLib::rPoetry,
       3575, AGRAMTABLib::rProfession,
       3587, AGRAMTABLib::rSuperlative,
       3600, AGRAMTABLib::rPositive,
       3610, AGRAMTABLib::NOUN,
       3615, AGRAMTABLib::ADJ_FULL,
       3624, AGRAMTABLib::VERB,
       3629, AGRAMTABLib::PRONOUN,
       3637, AGRAMTABLib::PRONOUN_P,
       3647, AGRAMTABLib::PRONOUN_PREDK,
       3661, AGRAMTABLib::NUMERAL,
       3669, AGRAMTABLib::NUMERAL_P,
       3679, AGRAMTABLib::ADV,
       3683, AGRAMTABLib::PREDK,
       3689, AGRAMTABLib::PREP,
       3694, AGRAMTABLib::POSL,
       3699, AGRAMTABLib::CONJ,
       3704, AGRAMTABLib::INTERJ,
       3711, AGRAMTABLib::INP,
       3715, AGRAMTABLib::PHRASE,
       3722, AGRAMTABLib::PARTICLE,
       3731, AGRAMTABLib::ADJ_SHORT,
       3741, AGRAMTABLib::PARTICIPLE,
       3752, AGRAMTABLib::ADVERB_PARTICIPLE,
       3770, AGRAMTABLib::PARTICIPLE_SHORT,
       3787, AGRAMTABLib::INFINITIVE,

        0        // eod
};

static const char qt_meta_enumstringdata_AGRAMTABLib[] = {
    "__MIDL___MIDL_itf_agramtab_0000_0001_0001\0__MIDL___MIDL_itf_agramtab_0000_0001_0002\0"
    "eGrammems\0ePartOfSpeeches\0gGrammems\0gPartOfSpeeches\0rGrammems\0rPartOfSpeeches\0"
    "VERB_PERS_T\0ADVERB_PARTICIPLE_T\0PARTICIPLE_SHORT_T\0ADJ_SHORT_T\0PREDK_T\0PARTICIPLE_T\0INFINITIVE_T\0INP_T\0DASH_T\0UNDETACHED_ADJ_PATIC\0"
    "COMPARATIVE_T\0COPUL_T\0"
    "VERBSATZ_T\0PARTIZIPIALSATZ_T\0INFINITIVSATZ_T\0"
    "eSingular\0ePlural\0eMasculinum\0eFeminum\0eAnimative\0ePerfective\0eNominative\0eObjectCase\0eNarrative\0eGeographics\0eProper\0ePersonalPronoun\0"
    "ePossessive\0ePredicative\0eUncountable\0eReflexivePronoun\0eDemonstrativePronoun\0eMass\0eComparativ\0eSupremum\0eFirstPerson\0eSecondPerson\0eThirdPerson\0ePresentIndef\0eInfinitive\0ePastIndef\0ePastParticiple\0eGerund\0"
    "eFuturum\0eConditional\0eApostropheS\0eApostrophe\0eNames\0eOrganisation\0"
    "eNOUN\0eADJ\0eVERB\0eVBE\0eMOD\0eNUMERAL\0eCONJ\0eINTERJ\0ePREP\0ePARTICLE\0eART\0eADV\0ePN\0eORDNUM\0ePRON\0ePOSS\0ePN_ADJ\0"
    "gNoaUnk\0gPredikBenutz\0gProUnk\0"
    "gTmpUnk\0gNac\0gMou\0gCou\0gGeo\0gWasser\0gGeb\0gStd\0gLok\0gVor\0gSichAcc\0gSichDat\0gSchwach\0gNichtSchwach\0gModal\0gAuxiliar\0gKonj1\0gKonj2\0gPartizip1\0gPartizip2\0gZuVerbForm\0gImperativ\0gPraeteritum\0gPrasens\0gGrundform\0"
    "gKomparativ\0gSuperlativ\0gProportionalKonjunktion\0gInfinitiv\0gVergleichsKonjunktion\0gNebenordnende\0gUnterordnende\0gPersonal\0gDemonstrativ\0gInterrogativ\0gPossessiv\0gReflexiv\0gRinPronomen\0gAlgPronomen\0gAdjektiveOhneArtikel\0"
    "gAdjektiveMitUnbestimmte\0gAdjektiveMitBestimmte\0gErstePerson\0gZweitePerson\0gDrittePerson\0gFeminin\0gMaskulin\0gNeutrum\0gPlural\0gSingular\0gNominativ\0gGenitiv\0gDativ\0gAkkusativ\0gAbbreviation\0gEinwohner\0gTransitiv\0"
    "gIntransitiv\0gImpersonal\0"
    "gART\0gADJ\0gADV\0gEIG\0gSUB\0gVER\0gPA1\0gPA2\0gPRONOMEN\0gPRP\0gKON\0gNEG\0gINJ\0gZAL\0gZUS\0gPRO_BEG\0gZU_INFINITIV\0"
    "rPlural\0rSingular\0rAllNumbers\0rNominativ\0rGenitiv\0rDativ\0rAccusativ\0rInstrumentalis\0"
    "rLocativ\0rVocativ\0rAllCases\0rMasculinum\0rFeminum\0rNeutrum\0rMascFem\0rAllGenders\0rPresentTense\0rFutureTense\0rPastTense\0rAllTimes\0rFirstPerson\0rSecondPerson\0rThirdPerson\0rAllPersons\0rImperative\0rAnimative\0"
    "rNonAnimative\0rAllAnimative\0rComparative\0rPerfective\0rNonPerfective\0rNonTransitive\0rTransitive\0rActiveVoice\0rPassiveVoice\0rIndeclinable\0rInitialism\0rPatronymic\0rToponym\0rOrganisation\0rQualitative\0rDeFactoSingTantum\0"
    "rInterrogative\0rDemonstrative\0rName\0rSurName\0rImpersonal\0rSlang\0rMisprint\0rColloquial\0rPossessive\0rArchaism\0rSecondCase\0rPoetry\0rProfession\0rSuperlative\0rPositive\0"
    "NOUN\0ADJ_FULL\0VERB\0PRONOUN\0PRONOUN_P\0PRONOUN_PREDK\0"
    "NUMERAL\0NUMERAL_P\0ADV\0PREDK\0PREP\0POSL\0CONJ\0INTERJ\0INP\0PHRASE\0PARTICLE\0ADJ_SHORT\0PARTICIPLE\0ADVERB_PARTICIPLE\0PARTICIPLE_SHORT\0INFINITIVE\0"

};

static const char *qt_meta_stringdata_AGRAMTABLib__RusGramTab() {
    static const char stringdata0[] = {
    "AGRAMTABLib::RusGramTab\0"
    "Interface 0\0IGramTab\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "FindGrammem(QString,qlonglong)\0gram_codes,grammems\0"
    "int\0\0GetAllGrammems(QString)\0gram_code\0qlonglong\0\0GetClauseNameByType(int)\0type\0QString\0\0GetClauseTypeByName(QString)\0bstrTypeName\0int\0\0GetClauseTypeByNameIfCan(QString,int&)\0bstrTypeName,lType\0int\0\0GetGramCodeByGrammemsAndPartofSpeechIfCan(uint,qlonglong,QString&)\0"
    "Pos,grammems,gramcodes\0int\0\0GetGrammems(QString)\0gram_code\0qlonglong\0\0GetPartOfSpeech(QString)\0gram_code\0uint\0\0GetPartOfSpeechStr(uint)\0PartOfSpeech\0QString\0\0GleicheCaseNumber(QString,QString)\0gram_code1,gram_code2\0"
    "int\0\0GleicheGenderNumber(QString,QString)\0gram_code1,gram_code2\0int\0\0GleicheGenderNumberCase(QString,QString,QString)\0common_noun_gram_code,noun_gram_code,adj_gram_code\0int\0\0GleicheSubjectPredicate(QString,QString)\0"
    "gram_code1,gram_code2\0int\0\0GrammemsToStr(qlonglong)\0grammems\0QString\0\0HaveEqualPartOfSpeech(QString,QString)\0gram_code1,gram_code2\0int\0\0Load()\0\0\0\0ProcessPOSAndGrammems(QString,uint&,qlonglong&)\0in,PartOfSpeech,grammems\0"
    "\0\0ProcessPOSAndGrammemsIfCan(QString,uint&,qlonglong&)\0in,PartOfSpeech,grammems\0int\0\0"
    "GrammemsCount\0int\0PartOfSpeechCount\0uint\0"
    };
    static char data[sizeof(stringdata0) + sizeof(qt_meta_enumstringdata_AGRAMTABLib)];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
        memcpy(data + index, qt_meta_enumstringdata_AGRAMTABLib, sizeof(qt_meta_enumstringdata_AGRAMTABLib));
    }

    return data;
};

const QMetaObject RusGramTab::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_AGRAMTABLib__RusGramTab(),
qt_meta_data_AGRAMTABLib__RusGramTab }
};

void *RusGramTab::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_AGRAMTABLib__RusGramTab()))
        return static_cast<void*>(const_cast<RusGramTab*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_AGRAMTABLib__IGramTab[] = {

 // content:
       1,       // revision
       0,       // classname
       0,    0, // classinfo
       21,    10, // methods
       3,    115, // properties
       8,    124, // enums/sets

 // signals: signature, parameters, type, tag, flags
       22, 61, 83, 84, 5,
       85, 110, 115, 116, 5,
       117, 143, 158, 159, 5,

 // slots: signature, parameters, type, tag, flags
       160, 191, 211, 215, 9,
       216, 240, 250, 260, 9,
       261, 286, 291, 299, 9,
       300, 329, 342, 346, 9,
       347, 386, 405, 409, 9,
       410, 477, 500, 504, 9,
       505, 526, 536, 546, 9,
       547, 572, 582, 587, 9,
       588, 613, 626, 634, 9,
       635, 670, 692, 696, 9,
       697, 734, 756, 760, 9,
       761, 810, 861, 865, 9,
       866, 907, 929, 933, 9,
       934, 959, 968, 976, 9,
       977, 1016, 1038, 1042, 9,
       1043, 1050, 1051, 1052, 9,
       1053, 1101, 1126, 1127, 9,
       1128, 1181, 1206, 1210, 9,

 // properties: name, type, flags
       1211, 1225, 0x02005001, 		 // int GrammemsCount
       1229, 1247, 0x03005001, 		 // uint PartOfSpeechCount
       1252, 1260, 0x0a055003, 		 // QString control

 // enums: name, flags, count, data
       1268, 0x0, 12, 156, 
       1310, 0x0, 3, 180, 
       1352, 0x0, 34, 186, 
       1362, 0x0, 17, 254, 
       1378, 0x0, 62, 288, 
       1388, 0x0, 17, 412, 
       1404, 0x0, 57, 446, 
       1414, 0x0, 22, 560, 

 // enum data: key, value
       1430, AGRAMTABLib::VERB_PERS_T,
       1442, AGRAMTABLib::ADVERB_PARTICIPLE_T,
       1462, AGRAMTABLib::PARTICIPLE_SHORT_T,
       1481, AGRAMTABLib::ADJ_SHORT_T,
       1493, AGRAMTABLib::PREDK_T,
       1501, AGRAMTABLib::PARTICIPLE_T,
       1514, AGRAMTABLib::INFINITIVE_T,
       1527, AGRAMTABLib::INP_T,
       1533, AGRAMTABLib::DASH_T,
       1540, AGRAMTABLib::UNDETACHED_ADJ_PATIC,
       1561, AGRAMTABLib::COMPARATIVE_T,
       1575, AGRAMTABLib::COPUL_T,
       1583, AGRAMTABLib::VERBSATZ_T,
       1594, AGRAMTABLib::PARTIZIPIALSATZ_T,
       1612, AGRAMTABLib::INFINITIVSATZ_T,
       1628, AGRAMTABLib::eSingular,
       1638, AGRAMTABLib::ePlural,
       1646, AGRAMTABLib::eMasculinum,
       1658, AGRAMTABLib::eFeminum,
       1667, AGRAMTABLib::eAnimative,
       1678, AGRAMTABLib::ePerfective,
       1690, AGRAMTABLib::eNominative,
       1702, AGRAMTABLib::eObjectCase,
       1714, AGRAMTABLib::eNarrative,
       1725, AGRAMTABLib::eGeographics,
       1738, AGRAMTABLib::eProper,
       1746, AGRAMTABLib::ePersonalPronoun,
       1763, AGRAMTABLib::ePossessive,
       1775, AGRAMTABLib::ePredicative,
       1788, AGRAMTABLib::eUncountable,
       1801, AGRAMTABLib::eReflexivePronoun,
       1819, AGRAMTABLib::eDemonstrativePronoun,
       1841, AGRAMTABLib::eMass,
       1847, AGRAMTABLib::eComparativ,
       1859, AGRAMTABLib::eSupremum,
       1869, AGRAMTABLib::eFirstPerson,
       1882, AGRAMTABLib::eSecondPerson,
       1896, AGRAMTABLib::eThirdPerson,
       1909, AGRAMTABLib::ePresentIndef,
       1923, AGRAMTABLib::eInfinitive,
       1935, AGRAMTABLib::ePastIndef,
       1946, AGRAMTABLib::ePastParticiple,
       1962, AGRAMTABLib::eGerund,
       1970, AGRAMTABLib::eFuturum,
       1979, AGRAMTABLib::eConditional,
       1992, AGRAMTABLib::eApostropheS,
       2005, AGRAMTABLib::eApostrophe,
       2017, AGRAMTABLib::eNames,
       2024, AGRAMTABLib::eOrganisation,
       2038, AGRAMTABLib::eNOUN,
       2044, AGRAMTABLib::eADJ,
       2049, AGRAMTABLib::eVERB,
       2055, AGRAMTABLib::eVBE,
       2060, AGRAMTABLib::eMOD,
       2065, AGRAMTABLib::eNUMERAL,
       2074, AGRAMTABLib::eCONJ,
       2080, AGRAMTABLib::eINTERJ,
       2088, AGRAMTABLib::ePREP,
       2094, AGRAMTABLib::ePARTICLE,
       2104, AGRAMTABLib::eART,
       2109, AGRAMTABLib::eADV,
       2114, AGRAMTABLib::ePN,
       2118, AGRAMTABLib::eORDNUM,
       2126, AGRAMTABLib::ePRON,
       2132, AGRAMTABLib::ePOSS,
       2138, AGRAMTABLib::ePN_ADJ,
       2146, AGRAMTABLib::gNoaUnk,
       2154, AGRAMTABLib::gPredikBenutz,
       2168, AGRAMTABLib::gProUnk,
       2176, AGRAMTABLib::gTmpUnk,
       2184, AGRAMTABLib::gNac,
       2189, AGRAMTABLib::gMou,
       2194, AGRAMTABLib::gCou,
       2199, AGRAMTABLib::gGeo,
       2204, AGRAMTABLib::gWasser,
       2212, AGRAMTABLib::gGeb,
       2217, AGRAMTABLib::gStd,
       2222, AGRAMTABLib::gLok,
       2227, AGRAMTABLib::gVor,
       2232, AGRAMTABLib::gSichAcc,
       2241, AGRAMTABLib::gSichDat,
       2250, AGRAMTABLib::gSchwach,
       2259, AGRAMTABLib::gNichtSchwach,
       2273, AGRAMTABLib::gModal,
       2280, AGRAMTABLib::gAuxiliar,
       2290, AGRAMTABLib::gKonj1,
       2297, AGRAMTABLib::gKonj2,
       2304, AGRAMTABLib::gPartizip1,
       2315, AGRAMTABLib::gPartizip2,
       2326, AGRAMTABLib::gZuVerbForm,
       2338, AGRAMTABLib::gImperativ,
       2349, AGRAMTABLib::gPraeteritum,
       2362, AGRAMTABLib::gPrasens,
       2371, AGRAMTABLib::gGrundform,
       2382, AGRAMTABLib::gKomparativ,
       2394, AGRAMTABLib::gSuperlativ,
       2406, AGRAMTABLib::gProportionalKonjunktion,
       2431, AGRAMTABLib::gInfinitiv,
       2442, AGRAMTABLib::gVergleichsKonjunktion,
       2465, AGRAMTABLib::gNebenordnende,
       2480, AGRAMTABLib::gUnterordnende,
       2495, AGRAMTABLib::gPersonal,
       2505, AGRAMTABLib::gDemonstrativ,
       2519, AGRAMTABLib::gInterrogativ,
       2533, AGRAMTABLib::gPossessiv,
       2544, AGRAMTABLib::gReflexiv,
       2554, AGRAMTABLib::gRinPronomen,
       2567, AGRAMTABLib::gAlgPronomen,
       2580, AGRAMTABLib::gAdjektiveOhneArtikel,
       2602, AGRAMTABLib::gAdjektiveMitUnbestimmte,
       2627, AGRAMTABLib::gAdjektiveMitBestimmte,
       2650, AGRAMTABLib::gErstePerson,
       2663, AGRAMTABLib::gZweitePerson,
       2677, AGRAMTABLib::gDrittePerson,
       2691, AGRAMTABLib::gFeminin,
       2700, AGRAMTABLib::gMaskulin,
       2710, AGRAMTABLib::gNeutrum,
       2719, AGRAMTABLib::gPlural,
       2727, AGRAMTABLib::gSingular,
       2737, AGRAMTABLib::gNominativ,
       2748, AGRAMTABLib::gGenitiv,
       2757, AGRAMTABLib::gDativ,
       2764, AGRAMTABLib::gAkkusativ,
       2775, AGRAMTABLib::gAbbreviation,
       2789, AGRAMTABLib::gEinwohner,
       2800, AGRAMTABLib::gTransitiv,
       2811, AGRAMTABLib::gIntransitiv,
       2824, AGRAMTABLib::gImpersonal,
       2836, AGRAMTABLib::gART,
       2841, AGRAMTABLib::gADJ,
       2846, AGRAMTABLib::gADV,
       2851, AGRAMTABLib::gEIG,
       2856, AGRAMTABLib::gSUB,
       2861, AGRAMTABLib::gVER,
       2866, AGRAMTABLib::gPA1,
       2871, AGRAMTABLib::gPA2,
       2876, AGRAMTABLib::gPRONOMEN,
       2886, AGRAMTABLib::gPRP,
       2891, AGRAMTABLib::gKON,
       2896, AGRAMTABLib::gNEG,
       2901, AGRAMTABLib::gINJ,
       2906, AGRAMTABLib::gZAL,
       2911, AGRAMTABLib::gZUS,
       2916, AGRAMTABLib::gPRO_BEG,
       2925, AGRAMTABLib::gZU_INFINITIV,
       2939, AGRAMTABLib::rPlural,
       2947, AGRAMTABLib::rSingular,
       2957, AGRAMTABLib::rAllNumbers,
       2969, AGRAMTABLib::rNominativ,
       2980, AGRAMTABLib::rGenitiv,
       2989, AGRAMTABLib::rDativ,
       2996, AGRAMTABLib::rAccusativ,
       3007, AGRAMTABLib::rInstrumentalis,
       3023, AGRAMTABLib::rLocativ,
       3032, AGRAMTABLib::rVocativ,
       3041, AGRAMTABLib::rAllCases,
       3051, AGRAMTABLib::rMasculinum,
       3063, AGRAMTABLib::rFeminum,
       3072, AGRAMTABLib::rNeutrum,
       3081, AGRAMTABLib::rMascFem,
       3090, AGRAMTABLib::rAllGenders,
       3102, AGRAMTABLib::rPresentTense,
       3116, AGRAMTABLib::rFutureTense,
       3129, AGRAMTABLib::rPastTense,
       3140, AGRAMTABLib::rAllTimes,
       3150, AGRAMTABLib::rFirstPerson,
       3163, AGRAMTABLib::rSecondPerson,
       3177, AGRAMTABLib::rThirdPerson,
       3190, AGRAMTABLib::rAllPersons,
       3202, AGRAMTABLib::rImperative,
       3214, AGRAMTABLib::rAnimative,
       3225, AGRAMTABLib::rNonAnimative,
       3239, AGRAMTABLib::rAllAnimative,
       3253, AGRAMTABLib::rComparative,
       3266, AGRAMTABLib::rPerfective,
       3278, AGRAMTABLib::rNonPerfective,
       3293, AGRAMTABLib::rNonTransitive,
       3308, AGRAMTABLib::rTransitive,
       3320, AGRAMTABLib::rActiveVoice,
       3333, AGRAMTABLib::rPassiveVoice,
       3347, AGRAMTABLib::rIndeclinable,
       3361, AGRAMTABLib::rInitialism,
       3373, AGRAMTABLib::rPatronymic,
       3385, AGRAMTABLib::rToponym,
       3394, AGRAMTABLib::rOrganisation,
       3408, AGRAMTABLib::rQualitative,
       3421, AGRAMTABLib::rDeFactoSingTantum,
       3440, AGRAMTABLib::rInterrogative,
       3455, AGRAMTABLib::rDemonstrative,
       3470, AGRAMTABLib::rName,
       3476, AGRAMTABLib::rSurName,
       3485, AGRAMTABLib::rImpersonal,
       3497, AGRAMTABLib::rSlang,
       3504, AGRAMTABLib::rMisprint,
       3514, AGRAMTABLib::rColloquial,
       3526, AGRAMTABLib::rPossessive,
       3538, AGRAMTABLib::rArchaism,
       3548, AGRAMTABLib::rSecondCase,
       3560, AGRAMTABLib::rPoetry,
       3568, AGRAMTABLib::rProfession,
       3580, AGRAMTABLib::rSuperlative,
       3593, AGRAMTABLib::rPositive,
       3603, AGRAMTABLib::NOUN,
       3608, AGRAMTABLib::ADJ_FULL,
       3617, AGRAMTABLib::VERB,
       3622, AGRAMTABLib::PRONOUN,
       3630, AGRAMTABLib::PRONOUN_P,
       3640, AGRAMTABLib::PRONOUN_PREDK,
       3654, AGRAMTABLib::NUMERAL,
       3662, AGRAMTABLib::NUMERAL_P,
       3672, AGRAMTABLib::ADV,
       3676, AGRAMTABLib::PREDK,
       3682, AGRAMTABLib::PREP,
       3687, AGRAMTABLib::POSL,
       3692, AGRAMTABLib::CONJ,
       3697, AGRAMTABLib::INTERJ,
       3704, AGRAMTABLib::INP,
       3708, AGRAMTABLib::PHRASE,
       3715, AGRAMTABLib::PARTICLE,
       3724, AGRAMTABLib::ADJ_SHORT,
       3734, AGRAMTABLib::PARTICIPLE,
       3745, AGRAMTABLib::ADVERB_PARTICIPLE,
       3763, AGRAMTABLib::PARTICIPLE_SHORT,
       3780, AGRAMTABLib::INFINITIVE,

        0        // eod
};

static const char *qt_meta_stringdata_AGRAMTABLib__IGramTab() {
    static const char stringdata0[] = {
    "AGRAMTABLib::IGramTab\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "FindGrammem(QString,qlonglong)\0gram_codes,grammems\0int\0\0GetAllGrammems(QString)\0"
    "gram_code\0qlonglong\0\0GetClauseNameByType(int)\0type\0QString\0\0GetClauseTypeByName(QString)\0bstrTypeName\0int\0\0GetClauseTypeByNameIfCan(QString,int&)\0bstrTypeName,lType\0int\0\0GetGramCodeByGrammemsAndPartofSpeechIfCan(uint,qlonglong,QString&)\0"
    "Pos,grammems,gramcodes\0int\0\0GetGrammems(QString)\0gram_code\0qlonglong\0\0GetPartOfSpeech(QString)\0gram_code\0uint\0\0GetPartOfSpeechStr(uint)\0PartOfSpeech\0QString\0\0GleicheCaseNumber(QString,QString)\0gram_code1,gram_code2\0"
    "int\0\0GleicheGenderNumber(QString,QString)\0gram_code1,gram_code2\0int\0\0GleicheGenderNumberCase(QString,QString,QString)\0common_noun_gram_code,noun_gram_code,adj_gram_code\0int\0\0GleicheSubjectPredicate(QString,QString)\0"
    "gram_code1,gram_code2\0int\0\0GrammemsToStr(qlonglong)\0grammems\0QString\0\0HaveEqualPartOfSpeech(QString,QString)\0gram_code1,gram_code2\0int\0\0Load()\0\0\0\0ProcessPOSAndGrammems(QString,uint&,qlonglong&)\0in,PartOfSpeech,grammems\0"
    "\0\0ProcessPOSAndGrammemsIfCan(QString,uint&,qlonglong&)\0in,PartOfSpeech,grammems\0int\0\0"
    "GrammemsCount\0int\0PartOfSpeechCount\0uint\0control\0QString\0"
    };
    static char data[sizeof(stringdata0) + sizeof(qt_meta_enumstringdata_AGRAMTABLib)];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
        memcpy(data + index, qt_meta_enumstringdata_AGRAMTABLib, sizeof(qt_meta_enumstringdata_AGRAMTABLib));
    }

    return data;
};

const QMetaObject IGramTab::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_AGRAMTABLib__IGramTab(),
qt_meta_data_AGRAMTABLib__IGramTab }
};

void *IGramTab::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_AGRAMTABLib__IGramTab()))
        return static_cast<void*>(const_cast<IGramTab*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_AGRAMTABLib__EngGramTab[] = {

 // content:
       1,       // revision
       0,       // classname
       1,    10, // classinfo
       21,    12, // methods
       2,    117, // properties
       8,    123, // enums/sets

 // classinfo: key, value
       24, 36, 

 // signals: signature, parameters, type, tag, flags
       45, 84, 106, 107, 5,
       108, 133, 138, 139, 5,
       140, 166, 181, 182, 5,

 // slots: signature, parameters, type, tag, flags
       183, 214, 234, 238, 9,
       239, 263, 273, 283, 9,
       284, 309, 314, 322, 9,
       323, 352, 365, 369, 9,
       370, 409, 428, 432, 9,
       433, 500, 523, 527, 9,
       528, 549, 559, 569, 9,
       570, 595, 605, 610, 9,
       611, 636, 649, 657, 9,
       658, 693, 715, 719, 9,
       720, 757, 779, 783, 9,
       784, 833, 884, 888, 9,
       889, 930, 952, 956, 9,
       957, 982, 991, 999, 9,
       1000, 1039, 1061, 1065, 9,
       1066, 1073, 1074, 1075, 9,
       1076, 1124, 1149, 1150, 9,
       1151, 1204, 1229, 1233, 9,

 // properties: name, type, flags
       1234, 1248, 0x02005001, 		 // int GrammemsCount
       1252, 1270, 0x03005001, 		 // uint PartOfSpeechCount

 // enums: name, flags, count, data
       1275, 0x0, 12, 155, 
       1317, 0x0, 3, 179, 
       1359, 0x0, 34, 185, 
       1369, 0x0, 17, 253, 
       1385, 0x0, 62, 287, 
       1395, 0x0, 17, 411, 
       1411, 0x0, 57, 445, 
       1421, 0x0, 22, 559, 

 // enum data: key, value
       1437, AGRAMTABLib::VERB_PERS_T,
       1449, AGRAMTABLib::ADVERB_PARTICIPLE_T,
       1469, AGRAMTABLib::PARTICIPLE_SHORT_T,
       1488, AGRAMTABLib::ADJ_SHORT_T,
       1500, AGRAMTABLib::PREDK_T,
       1508, AGRAMTABLib::PARTICIPLE_T,
       1521, AGRAMTABLib::INFINITIVE_T,
       1534, AGRAMTABLib::INP_T,
       1540, AGRAMTABLib::DASH_T,
       1547, AGRAMTABLib::UNDETACHED_ADJ_PATIC,
       1568, AGRAMTABLib::COMPARATIVE_T,
       1582, AGRAMTABLib::COPUL_T,
       1590, AGRAMTABLib::VERBSATZ_T,
       1601, AGRAMTABLib::PARTIZIPIALSATZ_T,
       1619, AGRAMTABLib::INFINITIVSATZ_T,
       1635, AGRAMTABLib::eSingular,
       1645, AGRAMTABLib::ePlural,
       1653, AGRAMTABLib::eMasculinum,
       1665, AGRAMTABLib::eFeminum,
       1674, AGRAMTABLib::eAnimative,
       1685, AGRAMTABLib::ePerfective,
       1697, AGRAMTABLib::eNominative,
       1709, AGRAMTABLib::eObjectCase,
       1721, AGRAMTABLib::eNarrative,
       1732, AGRAMTABLib::eGeographics,
       1745, AGRAMTABLib::eProper,
       1753, AGRAMTABLib::ePersonalPronoun,
       1770, AGRAMTABLib::ePossessive,
       1782, AGRAMTABLib::ePredicative,
       1795, AGRAMTABLib::eUncountable,
       1808, AGRAMTABLib::eReflexivePronoun,
       1826, AGRAMTABLib::eDemonstrativePronoun,
       1848, AGRAMTABLib::eMass,
       1854, AGRAMTABLib::eComparativ,
       1866, AGRAMTABLib::eSupremum,
       1876, AGRAMTABLib::eFirstPerson,
       1889, AGRAMTABLib::eSecondPerson,
       1903, AGRAMTABLib::eThirdPerson,
       1916, AGRAMTABLib::ePresentIndef,
       1930, AGRAMTABLib::eInfinitive,
       1942, AGRAMTABLib::ePastIndef,
       1953, AGRAMTABLib::ePastParticiple,
       1969, AGRAMTABLib::eGerund,
       1977, AGRAMTABLib::eFuturum,
       1986, AGRAMTABLib::eConditional,
       1999, AGRAMTABLib::eApostropheS,
       2012, AGRAMTABLib::eApostrophe,
       2024, AGRAMTABLib::eNames,
       2031, AGRAMTABLib::eOrganisation,
       2045, AGRAMTABLib::eNOUN,
       2051, AGRAMTABLib::eADJ,
       2056, AGRAMTABLib::eVERB,
       2062, AGRAMTABLib::eVBE,
       2067, AGRAMTABLib::eMOD,
       2072, AGRAMTABLib::eNUMERAL,
       2081, AGRAMTABLib::eCONJ,
       2087, AGRAMTABLib::eINTERJ,
       2095, AGRAMTABLib::ePREP,
       2101, AGRAMTABLib::ePARTICLE,
       2111, AGRAMTABLib::eART,
       2116, AGRAMTABLib::eADV,
       2121, AGRAMTABLib::ePN,
       2125, AGRAMTABLib::eORDNUM,
       2133, AGRAMTABLib::ePRON,
       2139, AGRAMTABLib::ePOSS,
       2145, AGRAMTABLib::ePN_ADJ,
       2153, AGRAMTABLib::gNoaUnk,
       2161, AGRAMTABLib::gPredikBenutz,
       2175, AGRAMTABLib::gProUnk,
       2183, AGRAMTABLib::gTmpUnk,
       2191, AGRAMTABLib::gNac,
       2196, AGRAMTABLib::gMou,
       2201, AGRAMTABLib::gCou,
       2206, AGRAMTABLib::gGeo,
       2211, AGRAMTABLib::gWasser,
       2219, AGRAMTABLib::gGeb,
       2224, AGRAMTABLib::gStd,
       2229, AGRAMTABLib::gLok,
       2234, AGRAMTABLib::gVor,
       2239, AGRAMTABLib::gSichAcc,
       2248, AGRAMTABLib::gSichDat,
       2257, AGRAMTABLib::gSchwach,
       2266, AGRAMTABLib::gNichtSchwach,
       2280, AGRAMTABLib::gModal,
       2287, AGRAMTABLib::gAuxiliar,
       2297, AGRAMTABLib::gKonj1,
       2304, AGRAMTABLib::gKonj2,
       2311, AGRAMTABLib::gPartizip1,
       2322, AGRAMTABLib::gPartizip2,
       2333, AGRAMTABLib::gZuVerbForm,
       2345, AGRAMTABLib::gImperativ,
       2356, AGRAMTABLib::gPraeteritum,
       2369, AGRAMTABLib::gPrasens,
       2378, AGRAMTABLib::gGrundform,
       2389, AGRAMTABLib::gKomparativ,
       2401, AGRAMTABLib::gSuperlativ,
       2413, AGRAMTABLib::gProportionalKonjunktion,
       2438, AGRAMTABLib::gInfinitiv,
       2449, AGRAMTABLib::gVergleichsKonjunktion,
       2472, AGRAMTABLib::gNebenordnende,
       2487, AGRAMTABLib::gUnterordnende,
       2502, AGRAMTABLib::gPersonal,
       2512, AGRAMTABLib::gDemonstrativ,
       2526, AGRAMTABLib::gInterrogativ,
       2540, AGRAMTABLib::gPossessiv,
       2551, AGRAMTABLib::gReflexiv,
       2561, AGRAMTABLib::gRinPronomen,
       2574, AGRAMTABLib::gAlgPronomen,
       2587, AGRAMTABLib::gAdjektiveOhneArtikel,
       2609, AGRAMTABLib::gAdjektiveMitUnbestimmte,
       2634, AGRAMTABLib::gAdjektiveMitBestimmte,
       2657, AGRAMTABLib::gErstePerson,
       2670, AGRAMTABLib::gZweitePerson,
       2684, AGRAMTABLib::gDrittePerson,
       2698, AGRAMTABLib::gFeminin,
       2707, AGRAMTABLib::gMaskulin,
       2717, AGRAMTABLib::gNeutrum,
       2726, AGRAMTABLib::gPlural,
       2734, AGRAMTABLib::gSingular,
       2744, AGRAMTABLib::gNominativ,
       2755, AGRAMTABLib::gGenitiv,
       2764, AGRAMTABLib::gDativ,
       2771, AGRAMTABLib::gAkkusativ,
       2782, AGRAMTABLib::gAbbreviation,
       2796, AGRAMTABLib::gEinwohner,
       2807, AGRAMTABLib::gTransitiv,
       2818, AGRAMTABLib::gIntransitiv,
       2831, AGRAMTABLib::gImpersonal,
       2843, AGRAMTABLib::gART,
       2848, AGRAMTABLib::gADJ,
       2853, AGRAMTABLib::gADV,
       2858, AGRAMTABLib::gEIG,
       2863, AGRAMTABLib::gSUB,
       2868, AGRAMTABLib::gVER,
       2873, AGRAMTABLib::gPA1,
       2878, AGRAMTABLib::gPA2,
       2883, AGRAMTABLib::gPRONOMEN,
       2893, AGRAMTABLib::gPRP,
       2898, AGRAMTABLib::gKON,
       2903, AGRAMTABLib::gNEG,
       2908, AGRAMTABLib::gINJ,
       2913, AGRAMTABLib::gZAL,
       2918, AGRAMTABLib::gZUS,
       2923, AGRAMTABLib::gPRO_BEG,
       2932, AGRAMTABLib::gZU_INFINITIV,
       2946, AGRAMTABLib::rPlural,
       2954, AGRAMTABLib::rSingular,
       2964, AGRAMTABLib::rAllNumbers,
       2976, AGRAMTABLib::rNominativ,
       2987, AGRAMTABLib::rGenitiv,
       2996, AGRAMTABLib::rDativ,
       3003, AGRAMTABLib::rAccusativ,
       3014, AGRAMTABLib::rInstrumentalis,
       3030, AGRAMTABLib::rLocativ,
       3039, AGRAMTABLib::rVocativ,
       3048, AGRAMTABLib::rAllCases,
       3058, AGRAMTABLib::rMasculinum,
       3070, AGRAMTABLib::rFeminum,
       3079, AGRAMTABLib::rNeutrum,
       3088, AGRAMTABLib::rMascFem,
       3097, AGRAMTABLib::rAllGenders,
       3109, AGRAMTABLib::rPresentTense,
       3123, AGRAMTABLib::rFutureTense,
       3136, AGRAMTABLib::rPastTense,
       3147, AGRAMTABLib::rAllTimes,
       3157, AGRAMTABLib::rFirstPerson,
       3170, AGRAMTABLib::rSecondPerson,
       3184, AGRAMTABLib::rThirdPerson,
       3197, AGRAMTABLib::rAllPersons,
       3209, AGRAMTABLib::rImperative,
       3221, AGRAMTABLib::rAnimative,
       3232, AGRAMTABLib::rNonAnimative,
       3246, AGRAMTABLib::rAllAnimative,
       3260, AGRAMTABLib::rComparative,
       3273, AGRAMTABLib::rPerfective,
       3285, AGRAMTABLib::rNonPerfective,
       3300, AGRAMTABLib::rNonTransitive,
       3315, AGRAMTABLib::rTransitive,
       3327, AGRAMTABLib::rActiveVoice,
       3340, AGRAMTABLib::rPassiveVoice,
       3354, AGRAMTABLib::rIndeclinable,
       3368, AGRAMTABLib::rInitialism,
       3380, AGRAMTABLib::rPatronymic,
       3392, AGRAMTABLib::rToponym,
       3401, AGRAMTABLib::rOrganisation,
       3415, AGRAMTABLib::rQualitative,
       3428, AGRAMTABLib::rDeFactoSingTantum,
       3447, AGRAMTABLib::rInterrogative,
       3462, AGRAMTABLib::rDemonstrative,
       3477, AGRAMTABLib::rName,
       3483, AGRAMTABLib::rSurName,
       3492, AGRAMTABLib::rImpersonal,
       3504, AGRAMTABLib::rSlang,
       3511, AGRAMTABLib::rMisprint,
       3521, AGRAMTABLib::rColloquial,
       3533, AGRAMTABLib::rPossessive,
       3545, AGRAMTABLib::rArchaism,
       3555, AGRAMTABLib::rSecondCase,
       3567, AGRAMTABLib::rPoetry,
       3575, AGRAMTABLib::rProfession,
       3587, AGRAMTABLib::rSuperlative,
       3600, AGRAMTABLib::rPositive,
       3610, AGRAMTABLib::NOUN,
       3615, AGRAMTABLib::ADJ_FULL,
       3624, AGRAMTABLib::VERB,
       3629, AGRAMTABLib::PRONOUN,
       3637, AGRAMTABLib::PRONOUN_P,
       3647, AGRAMTABLib::PRONOUN_PREDK,
       3661, AGRAMTABLib::NUMERAL,
       3669, AGRAMTABLib::NUMERAL_P,
       3679, AGRAMTABLib::ADV,
       3683, AGRAMTABLib::PREDK,
       3689, AGRAMTABLib::PREP,
       3694, AGRAMTABLib::POSL,
       3699, AGRAMTABLib::CONJ,
       3704, AGRAMTABLib::INTERJ,
       3711, AGRAMTABLib::INP,
       3715, AGRAMTABLib::PHRASE,
       3722, AGRAMTABLib::PARTICLE,
       3731, AGRAMTABLib::ADJ_SHORT,
       3741, AGRAMTABLib::PARTICIPLE,
       3752, AGRAMTABLib::ADVERB_PARTICIPLE,
       3770, AGRAMTABLib::PARTICIPLE_SHORT,
       3787, AGRAMTABLib::INFINITIVE,

        0        // eod
};

static const char *qt_meta_stringdata_AGRAMTABLib__EngGramTab() {
    static const char stringdata0[] = {
    "AGRAMTABLib::EngGramTab\0"
    "Interface 0\0IGramTab\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "FindGrammem(QString,qlonglong)\0gram_codes,grammems\0"
    "int\0\0GetAllGrammems(QString)\0gram_code\0qlonglong\0\0GetClauseNameByType(int)\0type\0QString\0\0GetClauseTypeByName(QString)\0bstrTypeName\0int\0\0GetClauseTypeByNameIfCan(QString,int&)\0bstrTypeName,lType\0int\0\0GetGramCodeByGrammemsAndPartofSpeechIfCan(uint,qlonglong,QString&)\0"
    "Pos,grammems,gramcodes\0int\0\0GetGrammems(QString)\0gram_code\0qlonglong\0\0GetPartOfSpeech(QString)\0gram_code\0uint\0\0GetPartOfSpeechStr(uint)\0PartOfSpeech\0QString\0\0GleicheCaseNumber(QString,QString)\0gram_code1,gram_code2\0"
    "int\0\0GleicheGenderNumber(QString,QString)\0gram_code1,gram_code2\0int\0\0GleicheGenderNumberCase(QString,QString,QString)\0common_noun_gram_code,noun_gram_code,adj_gram_code\0int\0\0GleicheSubjectPredicate(QString,QString)\0"
    "gram_code1,gram_code2\0int\0\0GrammemsToStr(qlonglong)\0grammems\0QString\0\0HaveEqualPartOfSpeech(QString,QString)\0gram_code1,gram_code2\0int\0\0Load()\0\0\0\0ProcessPOSAndGrammems(QString,uint&,qlonglong&)\0in,PartOfSpeech,grammems\0"
    "\0\0ProcessPOSAndGrammemsIfCan(QString,uint&,qlonglong&)\0in,PartOfSpeech,grammems\0int\0\0"
    "GrammemsCount\0int\0PartOfSpeechCount\0uint\0"
    };
    static char data[sizeof(stringdata0) + sizeof(qt_meta_enumstringdata_AGRAMTABLib)];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
        memcpy(data + index, qt_meta_enumstringdata_AGRAMTABLib, sizeof(qt_meta_enumstringdata_AGRAMTABLib));
    }

    return data;
};

const QMetaObject EngGramTab::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_AGRAMTABLib__EngGramTab(),
qt_meta_data_AGRAMTABLib__EngGramTab }
};

void *EngGramTab::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_AGRAMTABLib__EngGramTab()))
        return static_cast<void*>(const_cast<EngGramTab*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_AGRAMTABLib__GerGramTab[] = {

 // content:
       1,       // revision
       0,       // classname
       1,    10, // classinfo
       21,    12, // methods
       2,    117, // properties
       8,    123, // enums/sets

 // classinfo: key, value
       24, 36, 

 // signals: signature, parameters, type, tag, flags
       45, 84, 106, 107, 5,
       108, 133, 138, 139, 5,
       140, 166, 181, 182, 5,

 // slots: signature, parameters, type, tag, flags
       183, 214, 234, 238, 9,
       239, 263, 273, 283, 9,
       284, 309, 314, 322, 9,
       323, 352, 365, 369, 9,
       370, 409, 428, 432, 9,
       433, 500, 523, 527, 9,
       528, 549, 559, 569, 9,
       570, 595, 605, 610, 9,
       611, 636, 649, 657, 9,
       658, 693, 715, 719, 9,
       720, 757, 779, 783, 9,
       784, 833, 884, 888, 9,
       889, 930, 952, 956, 9,
       957, 982, 991, 999, 9,
       1000, 1039, 1061, 1065, 9,
       1066, 1073, 1074, 1075, 9,
       1076, 1124, 1149, 1150, 9,
       1151, 1204, 1229, 1233, 9,

 // properties: name, type, flags
       1234, 1248, 0x02005001, 		 // int GrammemsCount
       1252, 1270, 0x03005001, 		 // uint PartOfSpeechCount

 // enums: name, flags, count, data
       1275, 0x0, 12, 155, 
       1317, 0x0, 3, 179, 
       1359, 0x0, 34, 185, 
       1369, 0x0, 17, 253, 
       1385, 0x0, 62, 287, 
       1395, 0x0, 17, 411, 
       1411, 0x0, 57, 445, 
       1421, 0x0, 22, 559, 

 // enum data: key, value
       1437, AGRAMTABLib::VERB_PERS_T,
       1449, AGRAMTABLib::ADVERB_PARTICIPLE_T,
       1469, AGRAMTABLib::PARTICIPLE_SHORT_T,
       1488, AGRAMTABLib::ADJ_SHORT_T,
       1500, AGRAMTABLib::PREDK_T,
       1508, AGRAMTABLib::PARTICIPLE_T,
       1521, AGRAMTABLib::INFINITIVE_T,
       1534, AGRAMTABLib::INP_T,
       1540, AGRAMTABLib::DASH_T,
       1547, AGRAMTABLib::UNDETACHED_ADJ_PATIC,
       1568, AGRAMTABLib::COMPARATIVE_T,
       1582, AGRAMTABLib::COPUL_T,
       1590, AGRAMTABLib::VERBSATZ_T,
       1601, AGRAMTABLib::PARTIZIPIALSATZ_T,
       1619, AGRAMTABLib::INFINITIVSATZ_T,
       1635, AGRAMTABLib::eSingular,
       1645, AGRAMTABLib::ePlural,
       1653, AGRAMTABLib::eMasculinum,
       1665, AGRAMTABLib::eFeminum,
       1674, AGRAMTABLib::eAnimative,
       1685, AGRAMTABLib::ePerfective,
       1697, AGRAMTABLib::eNominative,
       1709, AGRAMTABLib::eObjectCase,
       1721, AGRAMTABLib::eNarrative,
       1732, AGRAMTABLib::eGeographics,
       1745, AGRAMTABLib::eProper,
       1753, AGRAMTABLib::ePersonalPronoun,
       1770, AGRAMTABLib::ePossessive,
       1782, AGRAMTABLib::ePredicative,
       1795, AGRAMTABLib::eUncountable,
       1808, AGRAMTABLib::eReflexivePronoun,
       1826, AGRAMTABLib::eDemonstrativePronoun,
       1848, AGRAMTABLib::eMass,
       1854, AGRAMTABLib::eComparativ,
       1866, AGRAMTABLib::eSupremum,
       1876, AGRAMTABLib::eFirstPerson,
       1889, AGRAMTABLib::eSecondPerson,
       1903, AGRAMTABLib::eThirdPerson,
       1916, AGRAMTABLib::ePresentIndef,
       1930, AGRAMTABLib::eInfinitive,
       1942, AGRAMTABLib::ePastIndef,
       1953, AGRAMTABLib::ePastParticiple,
       1969, AGRAMTABLib::eGerund,
       1977, AGRAMTABLib::eFuturum,
       1986, AGRAMTABLib::eConditional,
       1999, AGRAMTABLib::eApostropheS,
       2012, AGRAMTABLib::eApostrophe,
       2024, AGRAMTABLib::eNames,
       2031, AGRAMTABLib::eOrganisation,
       2045, AGRAMTABLib::eNOUN,
       2051, AGRAMTABLib::eADJ,
       2056, AGRAMTABLib::eVERB,
       2062, AGRAMTABLib::eVBE,
       2067, AGRAMTABLib::eMOD,
       2072, AGRAMTABLib::eNUMERAL,
       2081, AGRAMTABLib::eCONJ,
       2087, AGRAMTABLib::eINTERJ,
       2095, AGRAMTABLib::ePREP,
       2101, AGRAMTABLib::ePARTICLE,
       2111, AGRAMTABLib::eART,
       2116, AGRAMTABLib::eADV,
       2121, AGRAMTABLib::ePN,
       2125, AGRAMTABLib::eORDNUM,
       2133, AGRAMTABLib::ePRON,
       2139, AGRAMTABLib::ePOSS,
       2145, AGRAMTABLib::ePN_ADJ,
       2153, AGRAMTABLib::gNoaUnk,
       2161, AGRAMTABLib::gPredikBenutz,
       2175, AGRAMTABLib::gProUnk,
       2183, AGRAMTABLib::gTmpUnk,
       2191, AGRAMTABLib::gNac,
       2196, AGRAMTABLib::gMou,
       2201, AGRAMTABLib::gCou,
       2206, AGRAMTABLib::gGeo,
       2211, AGRAMTABLib::gWasser,
       2219, AGRAMTABLib::gGeb,
       2224, AGRAMTABLib::gStd,
       2229, AGRAMTABLib::gLok,
       2234, AGRAMTABLib::gVor,
       2239, AGRAMTABLib::gSichAcc,
       2248, AGRAMTABLib::gSichDat,
       2257, AGRAMTABLib::gSchwach,
       2266, AGRAMTABLib::gNichtSchwach,
       2280, AGRAMTABLib::gModal,
       2287, AGRAMTABLib::gAuxiliar,
       2297, AGRAMTABLib::gKonj1,
       2304, AGRAMTABLib::gKonj2,
       2311, AGRAMTABLib::gPartizip1,
       2322, AGRAMTABLib::gPartizip2,
       2333, AGRAMTABLib::gZuVerbForm,
       2345, AGRAMTABLib::gImperativ,
       2356, AGRAMTABLib::gPraeteritum,
       2369, AGRAMTABLib::gPrasens,
       2378, AGRAMTABLib::gGrundform,
       2389, AGRAMTABLib::gKomparativ,
       2401, AGRAMTABLib::gSuperlativ,
       2413, AGRAMTABLib::gProportionalKonjunktion,
       2438, AGRAMTABLib::gInfinitiv,
       2449, AGRAMTABLib::gVergleichsKonjunktion,
       2472, AGRAMTABLib::gNebenordnende,
       2487, AGRAMTABLib::gUnterordnende,
       2502, AGRAMTABLib::gPersonal,
       2512, AGRAMTABLib::gDemonstrativ,
       2526, AGRAMTABLib::gInterrogativ,
       2540, AGRAMTABLib::gPossessiv,
       2551, AGRAMTABLib::gReflexiv,
       2561, AGRAMTABLib::gRinPronomen,
       2574, AGRAMTABLib::gAlgPronomen,
       2587, AGRAMTABLib::gAdjektiveOhneArtikel,
       2609, AGRAMTABLib::gAdjektiveMitUnbestimmte,
       2634, AGRAMTABLib::gAdjektiveMitBestimmte,
       2657, AGRAMTABLib::gErstePerson,
       2670, AGRAMTABLib::gZweitePerson,
       2684, AGRAMTABLib::gDrittePerson,
       2698, AGRAMTABLib::gFeminin,
       2707, AGRAMTABLib::gMaskulin,
       2717, AGRAMTABLib::gNeutrum,
       2726, AGRAMTABLib::gPlural,
       2734, AGRAMTABLib::gSingular,
       2744, AGRAMTABLib::gNominativ,
       2755, AGRAMTABLib::gGenitiv,
       2764, AGRAMTABLib::gDativ,
       2771, AGRAMTABLib::gAkkusativ,
       2782, AGRAMTABLib::gAbbreviation,
       2796, AGRAMTABLib::gEinwohner,
       2807, AGRAMTABLib::gTransitiv,
       2818, AGRAMTABLib::gIntransitiv,
       2831, AGRAMTABLib::gImpersonal,
       2843, AGRAMTABLib::gART,
       2848, AGRAMTABLib::gADJ,
       2853, AGRAMTABLib::gADV,
       2858, AGRAMTABLib::gEIG,
       2863, AGRAMTABLib::gSUB,
       2868, AGRAMTABLib::gVER,
       2873, AGRAMTABLib::gPA1,
       2878, AGRAMTABLib::gPA2,
       2883, AGRAMTABLib::gPRONOMEN,
       2893, AGRAMTABLib::gPRP,
       2898, AGRAMTABLib::gKON,
       2903, AGRAMTABLib::gNEG,
       2908, AGRAMTABLib::gINJ,
       2913, AGRAMTABLib::gZAL,
       2918, AGRAMTABLib::gZUS,
       2923, AGRAMTABLib::gPRO_BEG,
       2932, AGRAMTABLib::gZU_INFINITIV,
       2946, AGRAMTABLib::rPlural,
       2954, AGRAMTABLib::rSingular,
       2964, AGRAMTABLib::rAllNumbers,
       2976, AGRAMTABLib::rNominativ,
       2987, AGRAMTABLib::rGenitiv,
       2996, AGRAMTABLib::rDativ,
       3003, AGRAMTABLib::rAccusativ,
       3014, AGRAMTABLib::rInstrumentalis,
       3030, AGRAMTABLib::rLocativ,
       3039, AGRAMTABLib::rVocativ,
       3048, AGRAMTABLib::rAllCases,
       3058, AGRAMTABLib::rMasculinum,
       3070, AGRAMTABLib::rFeminum,
       3079, AGRAMTABLib::rNeutrum,
       3088, AGRAMTABLib::rMascFem,
       3097, AGRAMTABLib::rAllGenders,
       3109, AGRAMTABLib::rPresentTense,
       3123, AGRAMTABLib::rFutureTense,
       3136, AGRAMTABLib::rPastTense,
       3147, AGRAMTABLib::rAllTimes,
       3157, AGRAMTABLib::rFirstPerson,
       3170, AGRAMTABLib::rSecondPerson,
       3184, AGRAMTABLib::rThirdPerson,
       3197, AGRAMTABLib::rAllPersons,
       3209, AGRAMTABLib::rImperative,
       3221, AGRAMTABLib::rAnimative,
       3232, AGRAMTABLib::rNonAnimative,
       3246, AGRAMTABLib::rAllAnimative,
       3260, AGRAMTABLib::rComparative,
       3273, AGRAMTABLib::rPerfective,
       3285, AGRAMTABLib::rNonPerfective,
       3300, AGRAMTABLib::rNonTransitive,
       3315, AGRAMTABLib::rTransitive,
       3327, AGRAMTABLib::rActiveVoice,
       3340, AGRAMTABLib::rPassiveVoice,
       3354, AGRAMTABLib::rIndeclinable,
       3368, AGRAMTABLib::rInitialism,
       3380, AGRAMTABLib::rPatronymic,
       3392, AGRAMTABLib::rToponym,
       3401, AGRAMTABLib::rOrganisation,
       3415, AGRAMTABLib::rQualitative,
       3428, AGRAMTABLib::rDeFactoSingTantum,
       3447, AGRAMTABLib::rInterrogative,
       3462, AGRAMTABLib::rDemonstrative,
       3477, AGRAMTABLib::rName,
       3483, AGRAMTABLib::rSurName,
       3492, AGRAMTABLib::rImpersonal,
       3504, AGRAMTABLib::rSlang,
       3511, AGRAMTABLib::rMisprint,
       3521, AGRAMTABLib::rColloquial,
       3533, AGRAMTABLib::rPossessive,
       3545, AGRAMTABLib::rArchaism,
       3555, AGRAMTABLib::rSecondCase,
       3567, AGRAMTABLib::rPoetry,
       3575, AGRAMTABLib::rProfession,
       3587, AGRAMTABLib::rSuperlative,
       3600, AGRAMTABLib::rPositive,
       3610, AGRAMTABLib::NOUN,
       3615, AGRAMTABLib::ADJ_FULL,
       3624, AGRAMTABLib::VERB,
       3629, AGRAMTABLib::PRONOUN,
       3637, AGRAMTABLib::PRONOUN_P,
       3647, AGRAMTABLib::PRONOUN_PREDK,
       3661, AGRAMTABLib::NUMERAL,
       3669, AGRAMTABLib::NUMERAL_P,
       3679, AGRAMTABLib::ADV,
       3683, AGRAMTABLib::PREDK,
       3689, AGRAMTABLib::PREP,
       3694, AGRAMTABLib::POSL,
       3699, AGRAMTABLib::CONJ,
       3704, AGRAMTABLib::INTERJ,
       3711, AGRAMTABLib::INP,
       3715, AGRAMTABLib::PHRASE,
       3722, AGRAMTABLib::PARTICLE,
       3731, AGRAMTABLib::ADJ_SHORT,
       3741, AGRAMTABLib::PARTICIPLE,
       3752, AGRAMTABLib::ADVERB_PARTICIPLE,
       3770, AGRAMTABLib::PARTICIPLE_SHORT,
       3787, AGRAMTABLib::INFINITIVE,

        0        // eod
};

static const char *qt_meta_stringdata_AGRAMTABLib__GerGramTab() {
    static const char stringdata0[] = {
    "AGRAMTABLib::GerGramTab\0"
    "Interface 0\0IGramTab\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "FindGrammem(QString,qlonglong)\0gram_codes,grammems\0"
    "int\0\0GetAllGrammems(QString)\0gram_code\0qlonglong\0\0GetClauseNameByType(int)\0type\0QString\0\0GetClauseTypeByName(QString)\0bstrTypeName\0int\0\0GetClauseTypeByNameIfCan(QString,int&)\0bstrTypeName,lType\0int\0\0GetGramCodeByGrammemsAndPartofSpeechIfCan(uint,qlonglong,QString&)\0"
    "Pos,grammems,gramcodes\0int\0\0GetGrammems(QString)\0gram_code\0qlonglong\0\0GetPartOfSpeech(QString)\0gram_code\0uint\0\0GetPartOfSpeechStr(uint)\0PartOfSpeech\0QString\0\0GleicheCaseNumber(QString,QString)\0gram_code1,gram_code2\0"
    "int\0\0GleicheGenderNumber(QString,QString)\0gram_code1,gram_code2\0int\0\0GleicheGenderNumberCase(QString,QString,QString)\0common_noun_gram_code,noun_gram_code,adj_gram_code\0int\0\0GleicheSubjectPredicate(QString,QString)\0"
    "gram_code1,gram_code2\0int\0\0GrammemsToStr(qlonglong)\0grammems\0QString\0\0HaveEqualPartOfSpeech(QString,QString)\0gram_code1,gram_code2\0int\0\0Load()\0\0\0\0ProcessPOSAndGrammems(QString,uint&,qlonglong&)\0in,PartOfSpeech,grammems\0"
    "\0\0ProcessPOSAndGrammemsIfCan(QString,uint&,qlonglong&)\0in,PartOfSpeech,grammems\0int\0\0"
    "GrammemsCount\0int\0PartOfSpeechCount\0uint\0"
    };
    static char data[sizeof(stringdata0) + sizeof(qt_meta_enumstringdata_AGRAMTABLib)];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
        memcpy(data + index, qt_meta_enumstringdata_AGRAMTABLib, sizeof(qt_meta_enumstringdata_AGRAMTABLib));
    }

    return data;
};

const QMetaObject GerGramTab::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_AGRAMTABLib__GerGramTab(),
qt_meta_data_AGRAMTABLib__GerGramTab }
};

void *GerGramTab::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_AGRAMTABLib__GerGramTab()))
        return static_cast<void*>(const_cast<GerGramTab*>(this));
    return QAxObject::qt_metacast(_clname);
}

